version: '3.7'

networks:
  pgadmin-network:
    driver: bridge

volumes:
  postgres-volume:
  pgadmin-volume:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    networks:
      - pgadmin-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - pgadmin-network
    volumes:
      - pgadmin-volume:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"